kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-credential
  namespace: default
data:
  cse.tcc.transaction.redis.host: redis-host
  cse.tcc.transaction.redis.port: redis-port
  cse.tcc.transaction.redis.password: redis-password
